#!/usr/bin/env bash
# SSTPA Tools installer (Linux / macOS).
#
# - verifies prerequisites (Docker Engine + Compose v2)
# - copies the packaged payload to the install prefix
# - generates deploy/.env with fresh random passwords (never shipped)
# - loads bundled container images for air-gapped hosts
# - trusts Caddy's local root CA so the GUI can reach https://localhost
# - installs the uninstaller
#
# The Backend is otherwise NOT started here; the Startup Software is the user
# entry point (SRS §4) and performs `docker compose up` on launch. The one
# exception is the CA-trust step (--skip-ca-trust to opt out): Caddy mints its
# local root CA on first startup, so when Docker is running the installer brings
# the stack up once to obtain and trust that certificate — without it the GUI's
# very first connection to https://localhost would fail on an untrusted cert.
#
# 2025 Nicholas Triska. All rights reserved. See NOTICE in the payload.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX=""
SKIP_DOCKER_CHECK=0
SKIP_CA_TRUST=0

usage() {
  cat <<'USAGE'
Usage: install.sh [--prefix PATH] [--skip-docker-check] [--skip-ca-trust]

Installs SSTPA Tools to PATH (default: /opt/sstpa-tools as root,
~/.local/share/sstpa-tools otherwise), generates deployment credentials,
loads bundled Docker images when present, and trusts Caddy's local root CA
(unless --skip-ca-trust) so the desktop GUI can reach https://localhost.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)
      PREFIX="${2:?--prefix requires a value}"
      shift 2
      ;;
    --skip-docker-check)
      SKIP_DOCKER_CHECK=1
      shift
      ;;
    --skip-ca-trust)
      SKIP_CA_TRUST=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${PREFIX}" ]]; then
  if [[ "$(id -u)" -eq 0 ]]; then
    PREFIX="/opt/sstpa-tools"
  else
    PREFIX="${HOME}/.local/share/sstpa-tools"
  fi
fi

echo "==> Checking prerequisites"
if [[ "${SKIP_DOCKER_CHECK}" -eq 0 ]]; then
  if ! command -v docker >/dev/null 2>&1; then
    echo "FAIL: Docker is required but not on PATH." >&2
    echo "      Install Docker Engine / Docker Desktop, then re-run install.sh." >&2
    exit 1
  fi
  if ! docker compose version >/dev/null 2>&1; then
    echo "FAIL: Docker Compose v2 is required ('docker compose' subcommand not available)." >&2
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "WARN: the Docker daemon is not reachable right now. Installation continues," >&2
    echo "      but Docker must be running before SSTPA Tools is started." >&2
  fi
fi

echo "==> Installing payload to ${PREFIX}"
mkdir -p "${PREFIX}"
tar -C "${SCRIPT_DIR}/payload" -cf - . | tar -C "${PREFIX}" -xf -
install -m 0755 "${SCRIPT_DIR}/uninstall.sh" "${PREFIX}/uninstall.sh" 2>/dev/null || true
install -m 0755 "${SCRIPT_DIR}/trust-ca.sh" "${PREFIX}/trust-ca.sh" 2>/dev/null || true

# Fresh deployment credentials: generated per-installation, never packaged.
ENV_FILE="${PREFIX}/deploy/.env"
random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}
if [[ -f "${ENV_FILE}" ]]; then
  echo "==> Keeping existing deployment credentials (${ENV_FILE})"
else
  echo "==> Generating deployment credentials (${ENV_FILE})"
  NEO4J_PW="$(random_secret)"
  GRAFANA_PW="$(random_secret)"
  cat > "${ENV_FILE}" <<ENVEOF
# SSTPA Tools deployment environment — generated by install.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Neo4j bakes its password into the neo4j-data volume on first startup; to
# change it later you must also 'docker compose down -v' (destroys data).
SSTPA_ENV=production

# Neo4j (used by both the neo4j service and the backend service)
SSTPA_NEO4J_PASSWORD=${NEO4J_PW}

# Grafana admin (dashboards at https://localhost/grafana/)
SSTPA_GRAFANA_USER=admin
SSTPA_GRAFANA_PASSWORD=${GRAFANA_PW}

# Caddy edge ports (host side). Change if 80/443 are already in use locally.
SSTPA_HTTP_PORT=80
SSTPA_HTTPS_PORT=443
ENVEOF
  chmod 600 "${ENV_FILE}"
fi

if [[ -d "${SCRIPT_DIR}/payload/images" ]] && command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  echo "==> Loading bundled container images"
  while IFS= read -r tarball; do
    docker load -i "${tarball}"
  done < <(find "${SCRIPT_DIR}/payload/images" -maxdepth 1 -type f -name '*.tar' | sort)
fi

# Trust Caddy's local root CA so the GUI webview can validate https://localhost.
# Best-effort: it brings the stack up once to mint the CA, so it only runs when
# Docker is reachable; failure never aborts the install.
TRUST_HELPER="${PREFIX}/trust-ca.sh"
if [[ "${SKIP_CA_TRUST}" -eq 1 ]]; then
  echo "==> Skipping Caddy CA trust (--skip-ca-trust)"
  echo "    Trust it later so the GUI can connect: ${TRUST_HELPER}"
elif command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1 && [[ -x "${TRUST_HELPER}" ]]; then
  echo "==> Trusting Caddy's local root CA (needed for the GUI to reach https://localhost)"
  if ! "${TRUST_HELPER}"; then
    echo "WARN: could not trust the Caddy CA automatically." >&2
    echo "      Run it yourself once the Backend is up: ${TRUST_HELPER}" >&2
  fi
else
  echo "==> Docker not running now; skipping Caddy CA trust."
  echo "    After first launch, trust it so the GUI can connect: ${TRUST_HELPER}"
fi

echo
echo "SSTPA Tools installed to ${PREFIX}"
echo
STARTUP_BIN="${PREFIX}/bundles/startup/bin/sstpa-startup"
if [[ -x "${STARTUP_BIN}" ]]; then
  echo "Launch SSTPA Tools:   ${STARTUP_BIN}"
  echo "  (starts the Backend, authenticates you — first run creates the"
  echo "   RootAdmin account — then opens the GUI; stops the Backend on exit)"
else
  echo "Startup binary for this platform was not bundled; start manually:"
  echo "  cd ${PREFIX}/deploy && docker compose up -d"
fi
if [[ -d "${PREFIX}/reference-data" ]]; then
  REF_ARTIFACT="$(find "${PREFIX}/reference-data" -maxdepth 1 -type f -name 'sstpa-ref-data-*.tar.gz' | sort | tail -n 1 || true)"
  if [[ -n "${REF_ARTIFACT}" ]]; then
    echo
    echo "Reference data artifact: ${REF_ARTIFACT}"
    echo "Load it once the Backend is healthy:"
    echo "  ${PREFIX}/deploy/load-reference-data.sh '${REF_ARTIFACT}' '${PREFIX}/deploy'"
  fi
fi
echo
echo "Uninstall: ${PREFIX}/uninstall.sh"
